# Generated by Django 3.2.8 on 2022-08-23 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_neo', '0006_advice_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advice',
            name='read',
        ),
    ]
