# Generated by Django 3.2.8 on 2022-07-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_alter_user_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='place',
            new_name='home_town',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/static/panel/img/empty-profile.png', upload_to=''),
        ),
    ]
