# Generated by Django 3.2.8 on 2022-07-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0018_user_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_profile_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
