# Generated by Django 3.2.8 on 2022-07-31 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0019_user_last_profile_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
