# Generated by Django 3.2.8 on 2022-08-05 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0020_user_sex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('CLI', 'Clinical Psychologist'), ('COU', 'Counseling Psychologist'), ('PST', 'Psychiatrist'), ('MFT', 'Marriage And Family Therapist'), ('SW', 'Social Worker'), ('PMT', 'Psychometrist'), ('OTR', 'Other')], default='OTR', max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
