# Generated by Django 3.2.8 on 2022-08-22 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0024_star'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_posted']},
        ),
    ]
