# Generated by Django 3.2.8 on 2022-08-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
