# Generated by Django 3.2.8 on 2022-07-30 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220730_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 7, 30, 12, 38, 29, 902251)),
        ),
        migrations.AlterField(
            model_name='user',
            name='place',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
