# Generated by Django 3.2.8 on 2022-07-30 12:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220730_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 7, 30, 12, 39, 45, 561085, tzinfo=utc)),
        ),
    ]
