# Generated by Django 3.2.8 on 2022-07-30 12:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 7, 30, 12, 41, 7, 199474, tzinfo=utc)),
        ),
    ]
