# Generated by Django 3.2.8 on 2022-07-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='place',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
