# Generated by Django 3.2.8 on 2022-07-31 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20220730_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='/empty-profile.png', upload_to='profile_pics'),
        ),
    ]
