# Generated by Django 3.2.8 on 2022-07-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_user_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='/empty-profile.png', upload_to='profile_pics'),
        ),
    ]
